version: '2'
services:
    main:
        #build: .
        image: jenca/contactfluxx
        ports:
            - 3000
        environment:
            - VIRTUAL_HOST
            - VIRTUAL_PORT=3000
        networks:
            - front
            - back
            - default
networks:
    front:
        external:
            name: "puffin_front"
    back:
        external:
            name: "puffin_back"
